import FieldsetTabs from "../../../src/components/FieldsetTabs";

export const HEIGHT_LIST = {
  'h-auto': 'Auto',
  'h-screen': 'Screen Height',
  'h-0': '0px',
  'h-px': '1px',
  'h-0.5': '0.125rem',
  'h-1': '0.25rem',
  'h-1.5': '0.375rem',
  'h-2': '0.5rem',
  'h-2.5': '0.625rem',
  'h-3': '0.75rem',
  'h-3.5': '0.875rem',
  'h-4': '1rem',
  'h-5': '1.25rem',
  'h-6': '1.5rem',
  'h-7': '1.75rem',
  'h-8': '2rem',
  'h-9': '2.25rem',
  'h-10': '2.5rem',
  'h-11': '2.75rem',
  'h-12': '3rem',
  'h-14': '3.5rem',
  'h-16': '4rem',
  'h-20': '5rem',
  'h-24': '6rem',
  'h-28': '7rem',
  'h-32': '8rem',
  'h-36': '9rem',
  'h-40': '10rem',
  'h-44': '11rem',
  'h-48': '12rem',
  'h-52': '13rem',
  'h-56': '14rem',
  'h-60': '15rem',
  'h-64': '16rem',
  'h-72': '18rem',
  'h-80': '20rem',
  'h-96': '24rem',
  'h-1/6': '16.67%',
  'h-1/5': '20%',
  'h-1/4': '25%',
  'h-1/3': '33.33%',
  'h-2/5': '40%',
  'h-1/2': '50%',
  'h-3/5': '60%',
  'h-2/3': '66.67%',
  'h-3/4': '75%',
  'h-4/5': '80%',
  'h-5/6': '83.33%',
  'h-full': '100%',
};

const list = Object.keys(HEIGHT_LIST).map(k => ({ title: HEIGHT_LIST[k], value: k }));

export default {
  title: 'Height (Responsive)',
  description: 'Defaults to "auto". 1rem = 16px. If one responsive height is missing, it defaults to the lower screen width, meaning if only the smallest is set, it applies to all.',
  name: 'responsive.height',
  type: 'object',
  options: {
    collapsible: true,
    includeDescriptionAboveTabs: true,
    includeTitleAboveTabs: true,
  },
  inputComponent: FieldsetTabs,
  fieldsets: [
    { name: "xs", title: "Default", options: { sortOrder: 10 } },
    { name: "sm", title: "> 640", options: { sortOrder: 20 } },
    { name: "md", title: "> 768", options: { sortOrder: 30 } },
    { name: "lg", title: "> 1024", options: { sortOrder: 40 } },
    { name: "xl", title: "> 1280", options: { sortOrder: 50 } },
  ],

  fields: [
    {
      title: 'XS (< 640)',
      name: 'xs',
      type: 'string',
      fieldset: 'xs',
      options: { list },
    },
    {
      title: 'SM (< 768)',
      name: 'sm',
      type: 'string',
      fieldset: 'sm',
      options: { list },
    },
    {
      title: 'MD (< 1024)',
      name: 'md',
      type: 'string',
      fieldset: 'md',
      options: { list },
    },
    {
      title: 'LG (< 1280)',
      name: 'lg',
      type: 'string',
      fieldset: 'lg',
      options: { list },
    },
    {
      title: 'XL (>= 1280)',
      name: 'xl',
      type: 'string',
      fieldset: 'xl',
      options: { list },
    },
  ],
};
